name = "GRASS"
uuid = "beaa24b3-4aa0-42b2-a8f3-c93b81cbd48b"
authors = ["Michael Palumbo"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
